### ISSUE TITLE
sampleNames is required column name and arguable should not be

### ISSUE THREAD

**Issue by malcook** [C3BI-pasteur-fr/UTechSCB-SCHNAPPs#6]
uploading my own SCE to SCHNAPPs gives me the error: "scEx - colData doesn't contain sampleNames" is 

same goes for `barcode`

assigning one allows me to proceed

**Comment by baj12** [comment]
I updated the Readme to better reflect the requirements for the SingleCellExpression object. You are right, it wasn't well documented. Hope this helps. Let me know when you run into any further problems. I try to respond more quickly.

A SingleCellExperiment object is needed with the following
colData: sampleNames , and barcode
rowData: Description , symbol, id (unique)
